# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5206\u7c7b\u540d')),
                ('desc', models.TextField(blank=True, max_length=400, verbose_name='\u63cf\u8ff0')),
                ('orderby', models.IntegerField(default='0', verbose_name='\u6392\u5e8f')),
            ],
        ),
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('content', models.TextField(max_length=60000, verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='\u4f5c\u8005')),
                ('orderby', models.IntegerField(default='0', verbose_name='\u6392\u5e8f')),
                ('tags', models.TextField(max_length=400, verbose_name='\u6807\u7b7e')),
                ('source', models.TextField(default='\u539f\u521b', max_length=100, verbose_name='\u6765\u6e90')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
    ]
