# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-08 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='icms.Category', verbose_name='\u680f\u76ee'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u680f\u76ee\u540d'),
        ),
    ]
