# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icms', '0004_auto_20170908_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='tags',
            field=models.CharField(blank=True, max_length=400, verbose_name='\u6807\u7b7e'),
        ),
    ]
