# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-11 07:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icms', '0005_auto_20170911_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='orderby',
            field=models.IntegerField(default=0, verbose_name='\u6392\u5e8f'),
        ),
    ]
