# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-14 02:34
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icms', '0007_auto_20170914_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entries',
            name='uploadfiles',
        ),
        migrations.AlterField(
            model_name='entries',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=60000, verbose_name='\u6587\u7ae0\u5185\u5bb9'),
        ),
    ]
